// <auto-generated />
using System;
using AvoApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AvoApi.Migrations
{
    [DbContext(typeof(AvocadoContext))]
    partial class AvocadoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("AvoApi.Data.Models.Avocado", b =>
                {
                    b.Property<int>("AvocadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AveragePrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExtraLargeBags")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LargeBags")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Plu4046")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Plu4225")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Plu4770")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SmallBags")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalBags")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalVolume")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("AvocadoId");

                    b.ToTable("Avocados");
                });
#pragma warning restore 612, 618
        }
    }
}
